name: Bug Report
description: File a bug report for the MovieVerse application
title: "[Bug]: "
labels: ["bug", "urgent", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        **Thank you for taking the time to fill out this bug report for the MovieVerse application!**
        Your feedback is crucial in helping us improve your experience.

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please describe the bug. What did you expect to happen instead?
      placeholder: Describe the bug and what you expected to occur.
      value: "I encountered a bug when..."
    validations:
      required: true

  - type: dropdown
    id: version
    attributes:
      label: App Version
      description: What version of the MovieVerse application are you using?
      options:
        - 2.0.1 (Stable)
        - 2.1.0 (Beta)
        - 2.1.1 (Alpha)
      default: 0
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: What platform(s) does the issue occur on?
      multiple: true
      options:
        - Web
        - iOS
        - Android
        - Windows
        - MacOS
        - Linux

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide a step-by-step description of how to reproduce the problem.
      placeholder: "1. Go to '...'\n2. Click on '....'\n3. Scroll down to '....'\n4. See error"
    validations:
      required: true

  - type: textarea
    id: expected-vs-actual
    attributes:
      label: Expected vs. Actual Behavior
      description: Please describe what you expected to happen and what actually happened.
      placeholder: "Expected: ...\nActual: ..."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs/Console Output
      description: Please include any relevant log messages or error outputs.
      placeholder: "Paste error logs or console output here."
      render: Shell

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://movie-verse.com/code-of-conduct)
      options:
        - label: I agree to follow the MovieVerse Code of Conduct.
          required: true
